# Week 4 · Day 2 — Assignment: Statistics Explorer
### Code to AI — Python & Data Science

---
**Instructions:**
- Complete every task. Write code under each `# YOUR CODE HERE` and add a short comment.
- Run All to make sure there are no errors.
- Save → push to GitHub → post the repo link in the WhatsApp group. ✅
- Due **before the next class**.

In [2]:
import numpy as np

## Task 1 — Your step count
Here are your daily step counts for one week:
`4000, 6500, 3000, 8000, 7200, 5000, 9000`

1. Store them in an array called `steps`.
2. Print the total, average, highest, and lowest steps.
3. Print the standard deviation (rounded to 2 decimals).

In [5]:
# YOUR CODE HERE
steps = np.array([4000, 6500, 3000, 8000, 7200, 5000, 9000])

print("average steps: ", steps.mean())
print("highest steps: ", steps.max())
print("lowest steps: ", steps.min())

print("Standardized deviation: ", steps.std())

average steps:  6100.0
highest steps:  9000
lowest steps:  3000
Standardized deviation:  2022.0216192146484


## Task 2 — Goal check with masks
Your daily step goal is **6000**.
1. Use a boolean mask to show only the days you hit the goal (≥ 6000).
2. Count how many days you hit the goal.
3. Show the days you missed it.

In [8]:
# YOUR CODE HERE

print(steps[steps >= 6000])
print(sum(steps >= 6000))
print(steps[steps < 6000])

[6500 8000 7200 9000]
4
[4000 3000 5000]


## Task 3 — Label your days with np.where
Create a label array from `steps`:
- `"GOAL"` if steps ≥ 6000
- `"MISS"` otherwise

Print the labels.

In [9]:
# YOUR CODE HERE

print(np.where(steps >= 6000 , "GOAL" , "MISS"))

['MISS' 'GOAL' 'MISS' 'GOAL' 'GOAL' 'MISS' 'GOAL']


## Task 4 — Work with a table (axis)
This 2D array shows 3 weeks × 4 subjects of quiz scores:

```
Week1: 8, 7, 9, 6
Week2: 5, 8, 7, 9
Week3: 9, 9, 8, 7
```

1. Build the 2D array called `quiz`.
2. Print each week's average (across rows).
3. Print each subject's average (down columns).

In [18]:
# YOUR CODE HERE
import numpy as np

quiz = np.array([[8, 7, 9, 6],
                [5, 8, 7, 9],
                [9, 9, 8, 7]])

print("week's row's average: ", quiz.mean(axis = 1))
print("week's colum's average: ", quiz.mean(axis = 0))

week's row's average:  [7.5  7.25 8.25]
week's colum's average:  [7.33333333 8.         8.         7.33333333]


## Task 5 — Reshape challenge
1. Use `np.arange` to make numbers from 1 to 20.
2. Reshape into 5 rows × 4 columns.
3. Print the sum of each column using `axis`.

In [21]:
# YOUR CODE HERE
arr = np.arange(1 , 21)

arr = arr.reshape(5 , 4)
print(arr)

print()
print(arr.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

[10 26 42 58 74]


### ✅ Before you submit
- [ ] Run All — no errors
- [ ] Short comment on each task
- [ ] Saved & pushed to GitHub
- [ ] Repo link posted in WhatsApp group

Excellent work — you're ready for the Day 3 project! 🎉